### ISSUE TITLE
Pipeline is unable to connect to https://quay.io in a network where outbound access is restricted to a proxy server

### ISSUE THREAD

**Issue by kammoji** [PacificBiosciences/HiFi-human-WGS-WDL#89]
**Describe the bug**
There's a connection problem to the pipeline's container service quay.io in our sensitive data network where outside access is enabled via proxy. Although a proxy setup is active via environment variables, the pipeline does not seem to recognize the setup as access to quay.io is attempted via port 443 instead of the proxy.

**Details**
- Release Version: 1.5.0
- Backend: Cromwell SMRT Link 12.0 bundled version (cromwell 74-unknown-SNAP) on HPC:
- Inputs: a BAM file of H.sapiens mapping data
- Failing task(s): SubWorkflowActor-SubWorkflow-sample_analysis

"
...
[2023-11-20 09:17:27,41] [info] b174f80d-0a6b-490c-a0f5-bde7b23a7c03-SubWorkflowActor-SubWorkflow-sample_analysis:0:1 [b174f80d]: Starting sample_analysis.pbmm2_align
[2023-11-20 09:17:30,74] [info] Assigned new job execution tokens to the following groups: 9b224c2f: 1
[2023-11-20 09:17:31,57] [info] Request threw an exception on attempt #1. Retrying after 92 milliseconds
org.http4s.client.ConnectionFailure: Error connecting to https://quay.io/ using address quay.io:443 (unresolved: false)
        at org.http4s.client.blaze.Http1Support.$anonfun$buildPipeline$1(Http1Support.scala:90)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        at async @ org.http4s.internal.package$.$anonfun$fromFuture$1(package.scala:144)
        at flatMap @ org.http4s.internal.package$.fromFuture(package.scala:139)
        at flatMap @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:119)
        at shift @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:119)
        at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:83)
        at unsafeRunSync @ cromwell.docker.DockerInfoActor.preStart(DockerInfoActor.scala:173)
Caused by: java.net.SocketException: Network is unreachable
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(Unknown Source)
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(Unknown Source)
        at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(Unknown Source)
        at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
...
"

The pipeline eventually terminates being unable to get the container from the service (after three attempts).

But, for reference, I am able to e.g. wget the quay.io index page via HTTPS in the current environment:

"
~$ wget https://quay.io/
--2023-11-20 09:23:47--  https://quay.io/
Resolving www-cache.OURDOMAIN_HERE.fi (www-cache.OURDOMAIN_HERE.fi)... OUR.SVM.IP.HERE
Connecting to www-cache.OURDOMAIN_HERE.fi (www-cache.OURDOMAIN_HERE.fi)|OUR.SVM.IP.HERE|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 76066 (74K) [text/html]
Saving to: ‘index.html’

index.html                                           100%[=====================================================================================================================>]  74.28K  --.-KB/s    in 0.1s   

2023-11-20 09:23:48 (772 KB/s) - ‘index.html’ saved [76066/76066]
"

Which environment variables do I need to define to make the pipeline use the proxy setup. Or can I specify the proxy address in the inputs.json file somehow?

**Expected behavior**
Connect to the container service using the proxy setup

**Additional context**
Here's a pseudonymized output of our environment variable setting regarding the proxy:
~$ env | grep -iF proxy
no_proxy=localhost,127.0.0.1,::1
https_proxy=http://www-cache.OURDOMAIN_HERE.fi:3128
NO_PROXY=localhost,127.0.0.1,::1
HTTPS_PROXY=http://www-cache.OURDOMAIN_HERE.fi:3128
HTTP_PROXY=http://www-cache.OURDOMAIN_HERE.fi:3128
http_proxy=http://www-cache.OURDOMAIN_HERE.fi:3128

The no_proxy/NO_PROXY variables we setup after having a live support session with one of PacBio developers. We were also encouraged to do a stop/start of the SMRT Link services on the server where we're running the pipeline and re-try. We did this, the output is the same.

Our case requires the use of a proxy as we are operating in a special network (intranet) audited for sensitive data where the inbound/outbound network access is highly restricted by law.

**Comment by williamrowell** [comment]
Hi,

Can you reach out through support@pacb.com, and I'll try to get you connected with someone who has a better understanding of proxies than me.  Please cc Bas and me (wrowell@pacificbiosciences.com) on the email, and link to this ticket.

Thanks!

Billy

**Comment by tanyasarkjain** [comment]
Im attempting to also run the pipeline with an HPC pipeline, via cromwell, and am getting the same issue with port 443 - was this resolved?

**Comment by williamrowell** [comment]
This is a known Cromwell issue, with multiple related issues and PRs filed.  Unfortunately, it looks like the Cromwell team doesn't have any plan to support proxies (https://github.com/broadinstitute/cromwell/pull/7114#issuecomment-1545803504).

It may be possible to cache the images yourself (as singularity images), replace the `docker:` URLs with local file paths, and adjust the `submit-docker:` command in your `cromwell.conf` to use singularity from your cache.  You probably won't have call caching though, since that depends on the internal Cromwell code for interacting with docker repos.

Will miniwdl work for your situation?

If you want to have a longer conversation about this, please email support@pacb.com.

**Comment by williamrowell** [comment]
A couple other potential solutions:
- https://github.com/biowdl/singularity-permanent-cache can be used to cache the images on your hpc, and you can cache from login nodes and hit the cache from compute nodes.  The biggest remaining issue will be that call caching won't work unless Cromwell has access to the Docker repos.
- You can set up a container repo server within your hpc cluster and host the images there instead.  Cromwell would be able to access the internal repo without using the proxy, and you'd have functional call-caching as well.

**Comment by tanyasarkjain** [comment]
Thank you unfortunately I don't think miniwdl would work as I am using SGE scheduler not slurm

**Comment by williamrowell** [comment]
Please send an email to support@pacb.com, mention that it's about using miniwdl+sge for the HiFi-human-WGS-WDL pipeline, and ask to include Billy on the ticket.  I think I might be able to help.

**Comment by tanyasarkjain** [comment]
Hi, I emailed support@pacb.com as you suggested, and asked if they could include Billy - but they seem unwilling to do so. 

They said "Adding support for another scheduler is something that would take significant development effort, and we don’t have a canned solution to hand to you.  This slurm version works on a variety of cloud platforms, though, so perhaps you’d want to consider running it that way if your local HPC only supports SGE? If you want to post a request on the github page, he can address it there."

I don't have access to cloud infrasture right now - my lab uses wonton (HPC) for its processing, so I would prefer not to branch out to a whole different infrastructure right now just to use this pipeline, if its at all possible to install on SGE.
